version: '3.8'

services:
  mvidarr:
    image: ghcr.io/prefect421/mvidarr:latest
    entrypoint: >
      sh -c "
        echo 'Waiting for MariaDB to be ready...';
        # Wait for MariaDB port to be available
        while ! nc -z mariadb 3306; do
          echo 'MariaDB port not ready, waiting...';
          sleep 3;
        done;
        echo 'MariaDB port is ready, waiting for database initialization...';
        # Additional wait for MariaDB to fully initialize
        sleep 10;
        # Test database connection before starting app
        while ! mysqladmin ping -h mariadb -u mvidarr -pmvidar123 --silent; do
          echo 'Database user not ready, waiting...';
          sleep 5;
        done;
        echo 'Database user is ready, starting application...';
        echo 'Creating required directories...';
        mkdir -p /app/data/database /app/data/thumbnails/artists /app/data/cache /app/data/downloads /app/data/logs /app/data/musicvideos /app/data/music_videos;
        chown -R mvidarr:mvidarr /app/data;
        touch /app/data/database/.initialized || true;
        echo 'Starting MVidarr application...';
        cd /app && su mvidarr -c 'python3 app.py';
      "
    container_name: mvidarr
    ports:
      - "0.0.0.0:5050:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=mvidarr
      - DB_PASSWORD=mvidar123               # ✅ Consistent password
      - DB_NAME=mvidarr
      - SECRET_KEY=thisisthesecret
      - MVIDARR_SECRET_KEY=donttellthesecret
      - IMVDB_API_KEY=
      - YOUTUBE_API_KEY=
      - PORT=5000
      - DEBUG=false
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    volumes:
      - /home/mike/Docker_Drives/mvidarr-dev/data/downloads:/app/data/downloads
      - /mnt/media/MusicVideos:/app/data/musicvideos
      - /home/mike/Docker_Drives/mvidarr-dev/data/database:/app/data/database
      - /home/mike/Docker_Drives/mvidarr-dev/data/thumbnails:/app/data/thumbnails
      - /home/mike/Docker_Drives/mvidarr-dev/data/logs:/app/data/logs
      - /home/mike/Docker_Drives/mvidarr-dev/data/cache:/app/data/cache
      - /home/mike/Docker_Drives/mvidarr-dev/config:/app/config
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mvidarr-network

  mariadb:
    image: mariadb:11.4
    container_name: mvidarr-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mvidarr
      - MYSQL_USER=mvidarr
      - MYSQL_PASSWORD=mvidar123             # ✅ Fixed: Now matches DB_PASSWORD
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
      - TZ=UTC
    volumes:
      - /home/mike/Docker_Drives/mvidarr-dev/database/mariadb:/var/lib/mysql
    ports:
      - "0.0.0.0:5051:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mvidarr", "-pmvidar123"]  # ✅ Test with app user
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - mvidarr-network

networks:
  mvidarr-network:
    driver: bridge