# These are supported funding model platforms

github: # Replace with GitHub Sponsors username if available
patreon: # Replace with a single Patreon username
open_collective: # Replace with Open Collective project name
ko_fi: https://ko-fi.com/prefect421
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: # Replace with a single custom sponsorship URL
