# Configuration for Label Actions - https://github.com/dessant/label-actions

'Type: Support':
  comment: >
    :wave: @{issue-author}, we use the issue tracker exclusively
    for bug reports and feature requests. However, this issue appears
    to be a support request. Please check the [documentation](https://github.com/prefect421/mvidarr/tree/main/docs) 
    or create a discussion for general questions.
  close: true
  close-reason: 'not planned'

'Status: Logs Needed':
  comment: >
    :wave: @{issue-author}, In order to help you further we'll need to see logs. 
    Please provide relevant log files from MVidarr (logs/mvidarr.log) or Docker logs (docker-compose logs).
    Make sure to enable debug logging if needed and replicate the problem.
