'Area: API':
  - changed-files:
      - any-glob-to-any-file: 'src/api/**/*'

'Area: Database':
  - changed-files:
      - any-glob-to-any-file: 'src/database/**/*'

'Area: Services':
  - changed-files:
      - any-glob-to-any-file: 'src/services/**/*'

'Area: Configuration':
  - changed-files:
      - any-glob-to-any-file: 'src/config/**/*'

'Area: Utils':
  - changed-files:
      - any-glob-to-any-file: 'src/utils/**/*'

'Area: UI':
  - changed-files:
      - any-glob-to-any-file:
          - 'static/**/*'
          - 'templates/**/*'

'Area: Docker':
  - changed-files:
      - any-glob-to-any-file:
          - 'docker-compose*.yml'
          - 'Dockerfile*'

'Area: Documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - 'README.md'
          - '*.md'
