# MVidarr GitHub Pages Configuration
title: MVidarr
description: >-
  A comprehensive music video management and discovery platform that helps you 
  organize, discover, and stream your music video collection with intelligent 
  artist management and advanced search capabilities.
baseurl: "/mvidarr"
url: "https://prefect421.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Site settings
author:
  name: MVidarr Team
  email: noreply@github.com

# Repository information
github_username: prefect421
repository: prefect421/mvidarr

# Navigation
header_pages:
  - about.md
  - installation.md
  - features.md
  - documentation.md
  - releases.md

# Minima theme settings
minima:
  skin: auto
  social_links:
    github: prefect421/mvidarr

# Exclude files from Jekyll processing
exclude:
  - .dockerignore
  - ".env*"
  - ".git*"
  - .python-version
  - __pycache__/
  - "*.pyc"
  - app.py
  - "requirements*.txt"
  - src/
  - frontend/
  - scripts/
  - migrations/
  - data/
  - logs/
  - "*.log"
  - "docker-compose*.yml"
  - "Dockerfile*"
  - entrypoint.sh
  - version.json
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - "Gemfile*"
  - "*.gem"
  - "*.gemspec"

# Include specific documentation files
include:
  - docs/
  - CHANGELOG.md
  - LICENSE