version: '3.8'

services:
  mvidarr:
    image: ghcr.io/prefect421/mvidarr:latest
    entrypoint: >
      sh -c "
        echo 'Waiting for MariaDB to be ready...';
        while ! nc -z mariadb 3306; do
          echo 'MariaDB not ready, waiting...';
          sleep 3;
        done;
        echo 'MariaDB is ready, starting application...';
        echo 'Creating required directories...';
        mkdir -p /app/data/database /app/data/thumbnails/artists /app/data/cache /app/data/downloads /app/data/logs /app/data/musicvideos /app/data/music_videos;
        chown -R mvidarr:mvidarr /app/data;
        touch /app/data/database/.initialized || true;
        echo 'Starting MVidarr application...';
        cd /app && su mvidarr -c 'python3 app.py';
      "
    container_name: mvidarr
    ports:
      - "0.0.0.0:${MVIDARR_PORT:-5001}:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=mvidarr
      - DB_PASSWORD=${DB_PASSWORD:-secure_password}
      - DB_NAME=mvidarr
      - SECRET_KEY=${SECRET_KEY:-mvidarr-dev-key-change-in-production}
      - MVIDARR_SECRET_KEY=${SECRET_KEY:-mvidarr-dev-key-change-in-production}
      - IMVDB_API_KEY=${IMVDB_API_KEY:-}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
      - PORT=5000
      - DEBUG=false
      - PYTHONUNBUFFERED=1
      - TZ=${TZ:-UTC}
    volumes:
      - ${DOWNLOADS_PATH:-./downloads}:/app/data/downloads
      - ${MUSIC_VIDEOS_PATH:-./music_videos}:/app/data/musicvideos
      - ${DATABASE_FOLDER:-./database}:/app/data/database
      - ${THUMBNAILS_PATH:-./thumbnails}:/app/data/thumbnails
      - ${LOGS_PATH:-./logs}:/app/data/logs
      - ${CACHE_PATH:-./cache}:/app/data/cache
      - ${CONFIG_PATH:-./config}:/app/config
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mvidarr-network

  mariadb:
    image: mariadb:11.4
    container_name: mvidarr-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=mvidarr
      - MYSQL_USER=mvidarr
      - MYSQL_PASSWORD=${DB_PASSWORD:-secure_password}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
      - TZ=${TZ:-UTC}
    volumes:
      - ${DATABASE_FOLDER:-./database}/mariadb:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "0.0.0.0:${MARIADB_PORT:-3307}:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - mvidarr-network

  # Optional: Reverse proxy for SSL termination and load balancing
  # Uncomment and configure if needed
  # nginx:
  #   image: nginx:alpine
  #   container_name: mvidarr-nginx
  #   ports:
  #     - "${HTTP_PORT:-80}:80"
  #     - "${HTTPS_PORT:-443}:443"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./docker/nginx/ssl:/etc/nginx/ssl:ro
  #     - ${LOGS_PATH:-./logs}/nginx:/var/log/nginx
  #   depends_on:
  #     - mvidarr
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   networks:
  #     - mvidarr-network

volumes:
  # Named volumes for internal container data
  # These are used when not mapping to host directories
  app_data:
    driver: local
  thumbnails_volume:
    driver: local
  logs_volume:
    driver: local
  cache_volume:
    driver: local

networks:
  mvidarr-network:
    driver: bridge