version: '3.8'

# Development Docker Compose configuration for MVidarr
# Includes hot reload, debug mode, and development-friendly settings

services:
  mvidarr-dev:
    build: 
      context: .
      dockerfile: Dockerfile.development
      target: development
    image: ghcr.io/prefect421/mvidarr:dev
    container_name: mvidarr-dev
    ports:
      - "${MVIDARR_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - DB_HOST=mariadb-dev
      - DB_PORT=3306
      - DB_USER=mvidarr
      - DB_PASSWORD=${DB_PASSWORD:-dev_password}
      - DB_NAME=mvidarr_dev
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key_change_in_production}
      - IMVDB_API_KEY=${IMVDB_API_KEY:-}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/__pycache__
      - /app/src/__pycache__
      # Data volumes for development
      - ${DOWNLOADS_PATH:-./data/downloads}:/app/data/downloads
      - ${MUSIC_VIDEOS_PATH:-./data/musicvideos}:/app/data/musicvideos
      - ${DATABASE_FOLDER:-./data/database}:/app/data/database
      - ${THUMBNAILS_PATH:-./data/thumbnails}:/app/data/thumbnails
      - ${LOGS_PATH:-./data/logs}:/app/data/logs
      - ${CACHE_PATH:-./data/cache}:/app/data/cache
      - ${BACKUPS_PATH:-./data/backups}:/app/data/backups
    depends_on:
      mariadb-dev:
        condition: service_healthy
    restart: unless-stopped
    # Development-specific health check (more frequent)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - mvidarr-dev-network

  mariadb-dev:
    image: mariadb:11.4
    container_name: mvidarr-dev-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-dev_root_password}
      - MYSQL_DATABASE=mvidarr_dev
      - MYSQL_USER=mvidarr
      - MYSQL_PASSWORD=${DB_PASSWORD:-dev_password}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
      - TZ=${TZ:-UTC}
    volumes:
      - ${DATABASE_FOLDER:-./data/database}/mariadb-dev:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    ports:
      - "${MARIADB_PORT:-3307}:3306"  # Different port for dev to avoid conflicts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - mvidarr-dev-network

  # Optional: Development database admin interface
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mvidarr-dev-phpmyadmin
    environment:
      - PMA_HOST=mariadb-dev
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-dev_root_password}
      - UPLOAD_LIMIT=512M
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on:
      mariadb-dev:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mvidarr-dev-network

volumes:
  # Development volumes - mapped to host for persistence
  dev_database:
    driver: local
  dev_thumbnails:
    driver: local
  dev_logs:
    driver: local
  dev_cache:
    driver: local

networks:
  mvidarr-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16