"""
OpenAPI Client Library Generation - Issue 128 Advanced FastAPI Features
Functions for generating clients using OpenAPI Generator (Java, Go, etc.)
"""

import json
import os
import subprocess
from typing import Any, Dict

from src.api.fastapi.client_models import ClientConfig, ClientLanguage, GeneratedClient
from src.utils.logger import get_logger

logger = get_logger("mvidarr.api.client_openapi_generator")


async def generate_openapi_client(
    spec: Dict[str, Any],
    config: ClientConfig,
    output_path: str,
    openapi_generator_jar: str,
) -> GeneratedClient:
    """Generate client using OpenAPI Generator (for Java, Go, etc.)"""
    try:
        if not openapi_generator_jar:
            raise ValueError("OpenAPI Generator JAR path not configured")

        # Generate OpenAPI spec
        spec_file = os.path.join(output_path, "openapi.json")
        with open(spec_file, "w") as f:
            json.dump(spec, f, indent=2)

        # Prepare generator command
        generator_name = get_openapi_generator_name(config.language)

        cmd = [
            "java",
            "-jar",
            openapi_generator_jar,
            "generate",
            "-i",
            spec_file,
            "-g",
            generator_name,
            "-o",
            output_path,
        ]

        # Add additional properties
        for key, value in config.additional_properties.items():
            cmd.extend(["--additional-properties", f"{key}={value}"])

        # Run generator
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"OpenAPI Generator failed: {result.stderr}")

        # Determine generated files (simplified)
        files_generated = ["Generated by OpenAPI Generator"]

        return GeneratedClient(
            language=config.language,
            package_name=config.package_name,
            version=config.version,
            output_path=output_path,
            files_generated=files_generated,
            examples_included=False,
            documentation_path=None,
            installation_instructions="See generated README",
        )

    except Exception as e:
        logger.error(f"Failed to generate OpenAPI client: {e}")
        raise


async def generate_custom_client(
    spec: Dict[str, Any], config: ClientConfig, output_path: str
) -> GeneratedClient:
    """Generate custom client for unsupported languages"""
    # Placeholder for custom client generation
    raise NotImplementedError(
        f"Custom client generation for {config.language.value} not implemented"
    )


def get_openapi_generator_name(language: ClientLanguage) -> str:
    """Get OpenAPI generator name for language"""
    generator_names = {
        ClientLanguage.JAVA: "java",
        ClientLanguage.GO: "go",
        ClientLanguage.CSHARP: "csharp",
        ClientLanguage.PHP: "php",
        ClientLanguage.RUBY: "ruby",
        ClientLanguage.SWIFT: "swift",
        ClientLanguage.RUST: "rust",
    }
    return generator_names.get(language, language.value)
