"""
Download Service Adapter - Backwards Compatibility Layer
Provides seamless integration with existing MVidarr code while using the new unified service
"""

import os
import tempfile
import time
from datetime import datetime
from typing import Any, Dict, Optional

from src.services.settings_service import settings
from src.services.unified_download_service import (
    AntiDetectionLevel,
    DownloadContext,
    unified_download_service,
)
from src.utils.filename_cleanup import FilenameCleanup
from src.utils.logger import get_logger

logger = get_logger("mvidarr.download_adapter")


class DownloadServiceAdapter:
    """
    Adapter that provides the old ytdlp_service interface while using the new unified service
    This allows gradual migration without breaking existing code
    """

    def __init__(self):
        self.unified_service = unified_download_service
        self.active_downloads = {}  # For backwards compatibility
        self.download_queue = []  # For backwards compatibility
        self.download_history = []  # For backwards compatibility

        # Initialize with existing settings
        self._load_settings()

        # Restore cookies from database if they exist
        self._restore_cookies_from_database()

        logger.info(
            "Download Service Adapter initialized - providing backwards compatibility"
        )

    def _load_settings(self):
        """Load settings that affect download behavior"""
        self.music_videos_path = settings.get("music_videos_path", "data/musicvideos")
        self.cookies_path = settings.get(
            "youtube_cookies_path", "data/cookies/youtube_cookies.txt"
        )

        # Ensure paths exist
        if not os.path.exists(self.music_videos_path):
            os.makedirs(self.music_videos_path, exist_ok=True)

    def _restore_cookies_from_database(self):
        """Restore YouTube cookies from database to filesystem on startup"""
        try:
            import base64

            from src.services.settings_service import SettingsService

            # Check if cookies exist in database
            cookie_content_b64 = SettingsService.get(
                "youtube_cookies_content", default=None
            )

            if cookie_content_b64:
                # Decode and write to file
                cookie_content = base64.b64decode(cookie_content_b64)

                # Ensure cookies directory exists
                cookie_dir = os.path.dirname(self.cookies_path)
                if not os.path.exists(cookie_dir):
                    os.makedirs(cookie_dir, exist_ok=True)

                # Write cookie file
                with open(self.cookies_path, "wb") as f:
                    f.write(cookie_content)

                logger.info(
                    f"Restored YouTube cookies from database to {self.cookies_path}"
                )
            else:
                logger.debug("No YouTube cookies found in database to restore")

        except Exception as e:
            logger.error(f"Failed to restore cookies from database: {e}")

    def _get_working_cookies_path(self) -> Optional[str]:
        """Write a fresh, disposable copy of the cookie file for yt-dlp to
        use (and freely rewrite) on this dispatch, sourced from the
        database -- the actual persistent source of truth (see
        _restore_cookies_from_database()) -- rather than handing yt-dlp
        self.cookies_path directly.

        #443 (live-reported): yt-dlp is given --cookies <path>, which it
        treats as BOTH input and output -- it rewrites the file after
        every invocation to persist session-refresh cookies, regardless
        of whether the download succeeded. Confirmed live on
        mvidarr-dev: after one failed attempt, the on-disk file (header
        rewritten to "generated by yt-dlp") was missing every core
        Google auth cookie (SID, HSID, SSID, APISID, SAPISID,
        LOGIN_INFO, SIDCC, __Secure-1PSID) that the freshly-uploaded
        database copy still had intact. Every subsequent attempt --
        including the other 2 of that same request's 3 retries, and any
        later retry -- then inherited the already-stripped, no-longer-
        authenticated file and failed with the exact same age-
        restriction error, even though the original upload was
        genuinely valid. Passing yt-dlp a disposable copy instead means
        whatever it does to that copy never propagates back to the
        database-backed master.

        Follow-up fix: the first version of this method used a single
        FIXED path (f"{cookies_path}.working") shared across every
        dispatch. Live on mvidarr-dev this was poisoned by a stale,
        differently-owned leftover file (created once, out-of-band, by
        a diagnostic script run as a different user than the real app
        process) -- every subsequent real download hit PermissionError
        writing to it, silently fell back to the master path, and
        reproduced the exact corruption bug this method exists to
        prevent. A fixed shared path is also a race between concurrent
        downloads. Each call now gets its own unique temp file, so no
        leftover file -- however it got there -- can ever block a later
        call again. Stale copies past the cleanup window (crashed
        processes, killed downloads) are opportunistically removed.
        """
        try:
            from src.services.settings_service import SettingsService

            cookie_content_b64 = SettingsService.get(
                "youtube_cookies_content", default=None
            )
            if not cookie_content_b64:
                # Nothing uploaded -- fall back to whatever's on disk,
                # matching this method's pre-existing no-cookies behavior.
                return self.cookies_path if os.path.exists(self.cookies_path) else None

            import base64

            cookie_content = base64.b64decode(cookie_content_b64)
            cookie_dir = os.path.dirname(self.cookies_path) or "."
            if not os.path.exists(cookie_dir):
                os.makedirs(cookie_dir, exist_ok=True)

            self._cleanup_stale_working_copies(cookie_dir)

            base_name = os.path.basename(self.cookies_path)
            fd, working_path = tempfile.mkstemp(
                prefix=f"{base_name}.", suffix=".working", dir=cookie_dir
            )
            try:
                with os.fdopen(fd, "wb") as f:
                    f.write(cookie_content)
            except Exception:
                os.unlink(working_path)
                raise
            return working_path
        except Exception as e:
            logger.error(f"Failed to prepare working cookie copy: {e}")
            return self.cookies_path if os.path.exists(self.cookies_path) else None

    def _cleanup_stale_working_copies(
        self, cookie_dir: str, max_age_seconds: int = 3600
    ) -> None:
        """Best-effort cleanup of leftover per-attempt working copies from
        previous dispatches (crashed processes, killed downloads, etc.)
        so they don't accumulate unboundedly. Never touches anything
        younger than max_age_seconds, so a copy actively in use by a
        concurrent in-flight download is never removed out from under
        it."""
        try:
            base_name = os.path.basename(self.cookies_path)
            now = time.time()
            for name in os.listdir(cookie_dir):
                if not (name.startswith(f"{base_name}.") and name.endswith(".working")):
                    continue
                full_path = os.path.join(cookie_dir, name)
                try:
                    if now - os.path.getmtime(full_path) > max_age_seconds:
                        os.unlink(full_path)
                except OSError:
                    pass
        except OSError:
            pass

    def add_music_video_download(
        self,
        artist: str,
        title: str,
        url: str,
        quality: str = "best",
        download_subtitles: bool = False,
        video_id: Optional[int] = None,
        download_id: Optional[int] = None,
        format_string: Optional[str] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Backwards compatible interface for adding downloads
        Maps to the new unified service while maintaining the same API
        """
        try:
            # Create output directory
            folder_name = FilenameCleanup.sanitize_folder_name(artist)
            output_path = os.path.join(self.music_videos_path, folder_name)
            os.makedirs(output_path, exist_ok=True)

            # Determine anti-detection level based on settings
            anti_detection_level = self._get_anti_detection_level()

            # Create download context
            # Use custom format string if provided (for quality upgrades), otherwise use quality
            context = DownloadContext(
                video_id=video_id or 0,
                url=url,
                title=FilenameCleanup.sanitize_folder_name(title),
                artist=artist,
                quality=format_string
                or quality,  # Pass format_string as quality if provided
                output_path=output_path,
                cookies_path=self._get_working_cookies_path(),
                anti_detection=anti_detection_level,
            )

            # Start download using unified service
            unified_download_id = self.unified_service.download_video(
                context, completion_callback=self._download_completion_callback
            )

            # Create backwards compatible response
            download_entry = {
                "id": unified_download_id,
                "artist": artist,
                "title": title,
                "url": url,
                "quality": quality,
                "status": "queued",
                "created_at": datetime.utcnow().isoformat(),
                "video_id": video_id,
                "download_id": download_id,
            }

            # Add to backwards compatibility structures
            self.active_downloads[unified_download_id] = download_entry
            self.download_queue.append(download_entry)

            logger.info(f"Queued download via adapter: {artist} - {title}")

            return {
                "success": True,
                "id": unified_download_id,
                "message": f"Download queued: {artist} - {title}",
            }

        except Exception as e:
            logger.error(f"Failed to queue download: {e}")
            return {
                "success": False,
                "error": str(e),
                "message": f"Failed to queue download: {str(e)}",
            }

    def _get_anti_detection_level(self) -> AntiDetectionLevel:
        """Determine anti-detection level based on system settings and history"""
        # Check if we've had recent detection issues
        # settings.get() returns strings from DB; 'False' is truthy in Python
        enable_aggressive_anti_detection = settings.get_bool(
            "enable_aggressive_anti_detection", False
        )

        if enable_aggressive_anti_detection:
            return AntiDetectionLevel.AGGRESSIVE

        # Default to moderate for good balance
        return AntiDetectionLevel.MODERATE

    def _download_completion_callback(self, download_id: int, result):
        """Handle download completion for backwards compatibility"""
        if download_id in self.active_downloads:
            download_entry = self.active_downloads[download_id]

            # Update status
            if result.success:
                download_entry["status"] = "completed"
                download_entry["file_path"] = result.file_path
                download_entry["file_size"] = result.file_size
                logger.info(f"Download {download_id} completed: {result.file_path}")
            else:
                download_entry["status"] = "failed"
                download_entry["error_message"] = result.error_message
                logger.error(f"Download {download_id} failed: {result.error_message}")

            download_entry["completed_at"] = datetime.utcnow().isoformat()

            # Move to history
            self.download_history.append(download_entry)
            del self.active_downloads[download_id]

            # Remove from queue
            self.download_queue = [
                d for d in self.download_queue if d["id"] != download_id
            ]

    def get_queue(self) -> Dict[str, Any]:
        """
        Get download queue status (backwards compatible)

        Delegates to unified download service for single source of truth
        """
        logger.info("Adapter get_queue: Delegating to unified download service")
        return self.unified_service.get_download_queue()

    def get_history(self, limit: int = 50) -> Dict[str, Any]:
        """
        Get download history (backwards compatible)

        Delegates to unified download service for single source of truth
        """
        logger.info(
            f"Adapter get_history: Delegating to unified download service (limit={limit})"
        )
        return self.unified_service.get_download_history(limit=limit)

    def health_check(self) -> Dict[str, Any]:
        """Health check for backwards compatibility"""
        try:
            version = self.unified_service.ytdlp_manager.get_version()
            return {
                "status": "healthy",
                "version": version,
                "message": "Unified download service operational",
            }
        except Exception as e:
            return {
                "status": "unhealthy",
                "error": str(e),
                "message": "Service health check failed",
            }

    def get_cookie_status(self) -> Dict[str, Any]:
        """
        Get cookie status (backwards compatible)

        Checks both filesystem and database for cookie availability
        Returns status from database if file doesn't exist (which is normal,
        as cookies are now stored in database and restored to file on demand)
        """
        # First check if file exists (fast path)
        if os.path.exists(self.cookies_path):
            try:
                stat = os.stat(self.cookies_path)
                return {
                    "cookies_available": True,
                    "file_path": self.cookies_path,
                    "file_size": stat.st_size,
                    "modified_time": stat.st_mtime,
                }
            except Exception as e:
                logger.warning(f"Failed to stat cookie file: {e}")
                # Fall through to database check

        # If file doesn't exist, check database (where cookies are actually stored)
        try:
            import base64

            from src.services.settings_service import SettingsService

            cookie_content_b64 = SettingsService.get(
                "youtube_cookies_content", default=None
            )

            if cookie_content_b64:
                # Cookies exist in database
                cookie_content = base64.b64decode(cookie_content_b64)
                file_size = len(cookie_content)

                # Get upload timestamp
                upload_timestamp = SettingsService.get(
                    "youtube_cookies_uploaded_at", default=None
                )

                if upload_timestamp:
                    modified_time = float(upload_timestamp)
                else:
                    modified_time = 0

                return {
                    "cookies_available": True,
                    "file_path": "database (persistent storage)",
                    "file_size": file_size,
                    "modified_time": modified_time,
                }
            else:
                return {
                    "cookies_available": False,
                    "error": "No cookies found in database or filesystem",
                }
        except Exception as e:
            logger.error(f"Failed to check cookie status in database: {e}")
            return {"cookies_available": False, "error": str(e)}

    def process_pending_downloads(self) -> Dict[str, Any]:
        """
        Process pending downloads - backwards compatible method

        Queries database for pending/queued downloads and starts them
        via the unified download service.

        Returns:
            Dict with success status, processed count, and any errors
        """
        try:
            from src.database.connection import get_db
            from src.database.models import Download, Video

            processed_count = 0
            errors = []

            with get_db() as session:
                # Find pending/queued downloads
                pending_downloads = (
                    session.query(Download)
                    .filter(Download.status.in_(["pending", "queued"]))
                    .limit(10)  # Process in batches to avoid overwhelming the system
                    .all()
                )

                logger.info(
                    f"Found {len(pending_downloads)} pending downloads to process"
                )

                for download in pending_downloads:
                    try:
                        # Get associated video
                        video = (
                            session.query(Video)
                            .filter(Video.id == download.video_id)
                            .first()
                        )

                        if not video:
                            logger.warning(
                                f"Download {download.id} references non-existent video {download.video_id}"
                            )
                            download.status = "failed"
                            download.error_message = "Video not found in database"
                            session.commit()
                            errors.append(
                                f"Download {download.id}: Video {download.video_id} not found"
                            )
                            continue

                        # Start download via unified service
                        logger.info(
                            f"Starting download {download.id}: {video.artist} - {video.title}"
                        )

                        # Use add_music_video_download to start the download
                        result = self.add_music_video_download(
                            artist=(
                                video.artist.name if video.artist else "Unknown Artist"
                            ),
                            title=video.title,
                            url=video.url,
                            quality=download.quality or "best",
                            video_id=video.id,
                            download_id=download.id,
                        )

                        if result.get("success"):
                            processed_count += 1
                            # Update download status to downloading
                            download.status = "downloading"
                            session.commit()
                        else:
                            error_msg = result.get("error", "Unknown error")
                            logger.error(
                                f"Failed to start download {download.id}: {error_msg}"
                            )
                            download.status = "failed"
                            download.error_message = error_msg
                            session.commit()
                            errors.append(f"Download {download.id}: {error_msg}")

                    except Exception as e:
                        logger.error(
                            f"Error processing download {download.id}: {e}",
                            exc_info=True,
                        )
                        errors.append(f"Download {download.id}: {str(e)}")
                        try:
                            download.status = "failed"
                            download.error_message = str(e)
                            session.commit()
                        except:
                            pass

            return {
                "success": True,
                "processed_count": processed_count,
                "found_pending": len(pending_downloads),
                "errors": errors,
                "message": f"Processed {processed_count} pending downloads",
            }

        except Exception as e:
            logger.error(f"Error in process_pending_downloads: {e}", exc_info=True)
            return {
                "success": False,
                "error": str(e),
                "message": f"Failed to process pending downloads: {str(e)}",
            }

    def cancel_download(self, download_id: int) -> bool:
        """Cancel download (backwards compatible)"""
        success = self.unified_service.cancel_download(download_id)

        if success and download_id in self.active_downloads:
            download_entry = self.active_downloads[download_id]
            download_entry["status"] = "cancelled"
            download_entry["completed_at"] = datetime.utcnow().isoformat()

            self.download_history.append(download_entry)
            del self.active_downloads[download_id]

            self.download_queue = [
                d for d in self.download_queue if d["id"] != download_id
            ]

        return success

    def stop_download(self, download_id: int) -> Dict[str, Any]:
        """Stop/cancel download (API compatibility method)"""
        success = self.cancel_download(download_id)

        if success:
            return {
                "success": True,
                "message": f"Download {download_id} stopped",
                "download_id": download_id,
                "error": None,
            }
        else:
            return {
                "success": False,
                "message": "Download not found or already completed",
                "download_id": download_id,
                "error": "Download not found",
            }

    def stop_video_download(self, video_id: int) -> Dict[str, Any]:
        """Stop a video stuck in the queue (video-sourced queue entry)"""
        success = self.unified_service.reset_stuck_video(video_id)

        if success:
            return {
                "success": True,
                "message": f"Video {video_id} download stopped",
                "download_id": None,
                "error": None,
            }
        else:
            return {
                "success": False,
                "message": "Video not found",
                "download_id": None,
                "error": "Video not found",
            }

    def retry_video_download(self, video_id: int) -> Dict[str, Any]:
        """Reset a stuck video back to WANTED so it can be redownloaded"""
        success = self.unified_service.reset_stuck_video(video_id)

        if success:
            return {
                "success": True,
                "message": f"Video {video_id} reset to WANTED for retry",
                "download_id": None,
                "error": None,
            }
        else:
            return {
                "success": False,
                "message": "Video not found",
                "download_id": None,
                "error": "Video not found",
            }

    def retry_download(self, download_id: int) -> Dict[str, Any]:
        """Retry a failed/stopped download (API compatibility method).

        Live-reported (#444): clicking Retry made the download vanish
        from both the queue and history widgets, then it silently
        appeared as downloaded a couple minutes later with no trace of
        the retry anywhere. Two compounding bugs:

        1. This method never actually re-dispatched anything -- it just
           set status="pending" and returned success, on the apparent
           assumption something else would notice and process it. Nothing
           did: process_queued_downloads() (the only code that queries
           for "pending" downloads) is only reachable via a manual
           POST /api/metube/process-queue call, never triggered
           automatically. The eventual "appeared as downloaded" was an
           unrelated coincidence (most likely the separate auto-download
           scheduler independently redownloading the same still-WANTED
           video through its own normal path), not this retry succeeding.
        2. Even setting that aside, "pending" isn't a status either the
           queue view (get_download_queue: queued/downloading) or the
           history view (get_download_history: completed/failed/
           cancelled) recognizes -- so a download genuinely left at
           "pending" for any reason is invisible in both places, exactly
           matching the reported symptom.

        Fix: actually claim the video and dispatch the download here,
        mirroring the claim-then-dispatch-then-revert-on-failure pattern
        already used by videos_downloads.py's queue_video_download() /
        queue_download_video() / bulk_download_videos(). On success the
        download settles at "queued" -- a status the queue view already
        recognizes. On failure it reverts to "failed" with a real error
        message, exactly where it started, instead of a silent "pending"
        that only vanishes.
        """
        try:
            from src.database.connection import get_db
            from src.database.models import Download, Video, VideoStatus
            from src.services.video_batch_service import claim_video_for_redownload

            with get_db() as session:
                download = (
                    session.query(Download).filter(Download.id == download_id).first()
                )

                if not download:
                    return {
                        "success": False,
                        "message": "Download not found",
                        "download_id": download_id,
                        "error": "Download not found",
                    }

                if download.status not in ["failed", "stopped", "cancelled"]:
                    return {
                        "success": False,
                        "message": f"Download is in '{download.status}' status and cannot be retried",
                        "download_id": download_id,
                        "error": f"Invalid status: {download.status}",
                    }

                if not download.video_id:
                    return {
                        "success": False,
                        "message": "Download has no associated video and cannot be re-dispatched",
                        "download_id": download_id,
                        "error": "Missing video_id",
                    }

                video = (
                    session.query(Video).filter(Video.id == download.video_id).first()
                )
                if not video:
                    return {
                        "success": False,
                        "message": "Associated video not found",
                        "download_id": download_id,
                        "error": "Video not found",
                    }

                original_status = video.status

                if not claim_video_for_redownload(download.video_id):
                    return {
                        "success": False,
                        "message": "Video is currently downloading and cannot be retried right now",
                        "download_id": download_id,
                        "error": "Failed to claim video for retry",
                    }

                # claim_video_for_redownload() commits DOWNLOADING via its
                # own, separate engine connection (deliberately, so it's
                # immune to whatever state this session already holds --
                # see its docstring). This session's own `video` object
                # was loaded before that claim and has no idea the row
                # changed underneath it, so SQLAlchemy's dirty-checking
                # would otherwise compare a later `video.status =
                # original_status` revert against its own stale, cached
                # belief (still whatever it loaded originally) and see no
                # real change -- silently skipping the UPDATE and leaving
                # the video stuck at DOWNLOADING forever on a dispatch
                # failure. Refreshing here makes this session's copy
                # agree with the real DB value first.
                session.refresh(video, attribute_names=["status"])

                download.status = "queued"
                download.progress = 0
                download.error_message = None
                download.updated_at = datetime.utcnow()
                session.commit()

                try:
                    result = self.add_music_video_download(
                        artist=video.artist.name if video.artist else "Unknown Artist",
                        title=video.title,
                        url=download.original_url,
                        quality=download.quality or "best",
                        video_id=download.video_id,
                        download_id=download.id,
                    )
                except Exception as dispatch_error:
                    result = {"success": False, "error": str(dispatch_error)}

                if not (result and result.get("success")):
                    dispatch_error_message = (
                        result.get("error", "Unknown dispatch error")
                        if result
                        else "Unknown dispatch error"
                    )
                    logger.error(
                        f"Retry dispatch failed for download {download_id}: {dispatch_error_message}"
                    )
                    video.status = original_status
                    download.status = "failed"
                    download.error_message = dispatch_error_message
                    session.commit()
                    return {
                        "success": False,
                        "message": f"Failed to retry download: {dispatch_error_message}",
                        "download_id": download_id,
                        "error": dispatch_error_message,
                    }

                logger.info(f"Download {download_id} re-dispatched for retry")

                return {
                    "success": True,
                    "message": f"Download {download_id} queued for retry",
                    "download_id": download_id,
                    "error": None,
                }

        except Exception as e:
            logger.error(f"Error retrying download {download_id}: {e}", exc_info=True)
            return {
                "success": False,
                "message": f"Failed to retry download: {str(e)}",
                "download_id": download_id,
                "error": str(e),
            }

    def clear_history(self, session=None) -> Dict[str, Any]:
        """
        Clear download history (backwards compatible)

        Clears both in-memory history and database records

        Args:
            session: Optional SQLAlchemy session to use (if None, creates its own)

        Returns:
            Dict with success status and deletion counts
        """
        try:
            # Clear in-memory history
            memory_count = len(self.download_history)
            self.download_history.clear()

            # Clear database records
            db_count = 0
            try:
                from src.database.models import Download

                # Use provided session or create a new one
                if session:
                    # Use existing session (FastAPI dependency injection)
                    db_count = session.query(Download).count()
                    session.query(Download).delete()
                    session.commit()
                    logger.info(f"Cleared {db_count} download records from database")
                else:
                    # Create own session (backward compatibility)
                    from src.database.connection import get_db

                    with get_db() as db_session:
                        db_count = db_session.query(Download).count()
                        db_session.query(Download).delete()
                        db_session.commit()
                        logger.info(
                            f"Cleared {db_count} download records from database"
                        )
            except Exception as db_error:
                logger.error(
                    f"Failed to clear download history from database: {db_error}",
                    exc_info=True,
                )
                # Continue even if DB fails - at least clear memory

            # Also clear download queue to prevent re-adding completed downloads
            cleared_queue_count = len(self.download_queue)
            self.download_queue.clear()

            total_count = memory_count + db_count
            logger.info(
                f"Cleared download history: {memory_count} from memory, "
                f"{db_count} from database, {cleared_queue_count} from queue"
            )

            return {
                "success": True,
                "message": f"Cleared {total_count} download records",
                "deleted_count": total_count,  # For frontend compatibility
                "memory_count": memory_count,
                "database_count": db_count,
                "queue_count": cleared_queue_count,
                "total_count": total_count,
            }

        except Exception as e:
            logger.error(f"Failed to clear download history: {e}", exc_info=True)
            return {
                "success": False,
                "error": str(e),
                "message": f"Failed to clear history: {str(e)}",
            }

    # Additional methods for full backwards compatibility
    def _resume_pending_downloads(self):
        """Resume pending downloads - now handled by unified service automatically"""
        logger.info("Resume pending downloads called - handled by unified service")
        pass

    def _update_database_download_status(
        self, download_entry, status, file_path=None, file_size=None, error=None
    ):
        """Database updates are now handled internally by unified service"""
        pass


# Global adapter instance for backwards compatibility
ytdlp_service = DownloadServiceAdapter()

# Also make it available under the old import path
import sys

sys.modules["src.services.ytdlp_service"] = sys.modules[__name__]
