name: Bug Report
description: 'Report a bug in MVidarr'
labels: ['Type: Bug', 'Status: Needs Triage']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an open or closed issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing open and closed issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **MVidarr Version**: v0.9.1
        - **Docker Install**: Yes
        - **Database**: MariaDB 11.4
        - **Browser**: Firefox 90 (If UI related)
    value: |
        - OS: 
        - MVidarr Version:
        - Docker Install:
        - Database:
        - Browser:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: |
      Please provide relevant log files from MVidarr (logs/mvidarr.log) or Docker logs (docker-compose logs).
      Tip: You can attach log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Logs have been provided as applicable
    description: Log files help diagnose issues faster
    options:
    - label: I have provided relevant log files that show this issue
      required: true