apiVersion: v1
kind: Service
metadata:
  name: {{ include "mvidarr.fullname" . }}
  namespace: {{ include "mvidarr.namespace" . }}
  labels:
    {{- include "mvidarr.labels" . | nindent 4 }}
    component: api
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "mvidarr.selectorLabels" . | nindent 4 }}
    component: api