# Site settings
title: MVidarr - Music Video Management Platform
description: A comprehensive music video management and discovery platform with intelligent automation, enterprise security, and modern streaming experience
baseurl: "/mvidarr"
url: "https://prefect421.github.io"

# Theme
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social links
github_username: prefect421

# Minima date format
minima:
  date_format: "%b %-d, %Y"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/