"""Fix for #443 (live-reported): after a genuine, valid cookie upload,
downloads still failed with "Sign in to confirm your age" -- even
though the upload mechanism itself was already confirmed correct
(writes to both the database and the on-disk file at the exact path
the download engine reads).

Root cause, confirmed live on mvidarr-dev: yt-dlp is invoked with
--cookies <path>, a flag it treats as BOTH input and output -- it
rewrites that exact file after every invocation to persist session-
refresh cookies, regardless of whether the download succeeded.
Comparing the database's pristine, freshly-uploaded copy of
youtube_cookies_content against the on-disk file after one failed
attempt showed the disk copy (header rewritten to "generated by
yt-dlp") was missing every core Google auth cookie the database copy
still had intact: SID, HSID, SSID, APISID, SAPISID, LOGIN_INFO, SIDCC,
__Secure-1PSID. Every subsequent attempt -- including the other 2 of
that same request's 3 retries, and any later retry, indefinitely,
until the next app restart re-restores from the database -- then
inherited the already-stripped, no-longer-authenticated file and
failed with the exact same error, even though the original upload was
genuinely valid.

Fix: DownloadServiceAdapter._get_working_cookies_path() writes a fresh,
disposable copy of the cookie file from the database (the real,
persistent source of truth) before every dispatch, and
add_music_video_download() passes yt-dlp that disposable copy instead
of self.cookies_path directly. Whatever yt-dlp does to its own working
copy can no longer propagate back to the database-backed master.
"""

import base64
import tempfile
from pathlib import Path
from unittest.mock import patch

from src.services.download_service_adapter import DownloadServiceAdapter


def _adapter(cookies_path):
    """Bypass __init__() (real filesystem/settings/subprocess work) --
    set only the one attribute _get_working_cookies_path() actually
    reads."""
    adapter = DownloadServiceAdapter.__new__(DownloadServiceAdapter)
    adapter.cookies_path = cookies_path
    return adapter


class TestGetWorkingCookiesPath:
    def test_writes_a_fresh_copy_from_the_database_when_cookies_are_uploaded(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cookies_path = str(Path(tmpdir) / "youtube_cookies.txt")
            adapter = _adapter(cookies_path)
            real_content = b"# Netscape HTTP Cookie File\nreal auth cookies here\n"
            b64_content = base64.b64encode(real_content).decode("utf-8")

            with patch(
                "src.services.settings_service.SettingsService.get",
                return_value=b64_content,
            ):
                working_path = adapter._get_working_cookies_path()

            assert working_path != cookies_path
            assert Path(working_path).read_bytes() == real_content

    def test_working_copy_is_separate_from_the_master_path(self):
        # The exact property that closes #443: yt-dlp must never be
        # handed the same path the upload endpoint and
        # _restore_cookies_from_database() write to.
        with tempfile.TemporaryDirectory() as tmpdir:
            cookies_path = str(Path(tmpdir) / "youtube_cookies.txt")
            Path(cookies_path).write_bytes(b"pre-existing master content")
            adapter = _adapter(cookies_path)

            with patch(
                "src.services.settings_service.SettingsService.get",
                return_value=base64.b64encode(b"fresh db content").decode("utf-8"),
            ):
                working_path = adapter._get_working_cookies_path()

            assert working_path != cookies_path
            # Mangling the working copy must never touch the master.
            Path(working_path).write_bytes(b"yt-dlp stripped this")
            assert Path(cookies_path).read_bytes() == b"pre-existing master content"

    def test_falls_back_to_the_disk_file_when_nothing_is_uploaded(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cookies_path = str(Path(tmpdir) / "youtube_cookies.txt")
            Path(cookies_path).write_bytes(b"only-on-disk, never uploaded via settings")
            adapter = _adapter(cookies_path)

            with patch(
                "src.services.settings_service.SettingsService.get",
                return_value=None,
            ):
                working_path = adapter._get_working_cookies_path()

            assert working_path == cookies_path

    def test_returns_none_when_nothing_is_uploaded_and_no_disk_file_exists(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cookies_path = str(Path(tmpdir) / "youtube_cookies.txt")
            adapter = _adapter(cookies_path)

            with patch(
                "src.services.settings_service.SettingsService.get",
                return_value=None,
            ):
                working_path = adapter._get_working_cookies_path()

            assert working_path is None


class TestAddMusicVideoDownloadUsesTheWorkingCopy:
    def test_passes_the_working_copy_path_not_the_master_path_to_the_download_context(
        self,
    ):
        with tempfile.TemporaryDirectory() as tmpdir:
            cookies_path = str(Path(tmpdir) / "youtube_cookies.txt")
            adapter = _adapter(cookies_path)
            adapter.music_videos_path = tmpdir

            captured_context = {}

            def _fake_download_video(self, context, completion_callback=None):
                captured_context["cookies_path"] = context.cookies_path
                return "fake-job-id"

            adapter.unified_service = type(
                "FakeUnifiedService", (), {"download_video": _fake_download_video}
            )()
            adapter.active_downloads = {}
            adapter.download_queue = []

            with patch(
                "src.services.settings_service.SettingsService.get",
                return_value=base64.b64encode(b"fresh cookies").decode("utf-8"),
            ), patch(
                "src.services.download_service_adapter.settings.get_bool",
                return_value=False,
            ):
                adapter.add_music_video_download(
                    artist="Test Artist", title="Test Song", url="https://x.test/v"
                )

            assert captured_context["cookies_path"] != cookies_path
            assert captured_context["cookies_path"].endswith(".working")
